### ISSUE TITLE
You are dicontinuing it.

### ISSUE THREAD

**Issue by dude2093350** [dguis/World-of-war-development-build#8]
You ruined my life. WAAAAAAAAAAAAAAAAAAAAAAAAAAAAWAAAAAAAAAAAAAAAAAAAAAAA

**Comment by dude2093350** [comment]
(NO You didn't really ruin my life you just made an awesome game why discontinued)

**Comment by dguis** [comment]
This is getting annoying.

**Comment by dguis** [comment]
By the way, if World of War is meant to be a collaborative project for D-Multi and cTech, please create the new repo <a href="https://github.com/organizations/D-Multi-cTech/repositories/new">here</a>.
